//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MUNI_INTEGRADOEntities : DbContext
    {
        public MUNI_INTEGRADOEntities()
            : base("name=MUNI_INTEGRADOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SM_ANEXO> SM_ANEXO { get; set; }
        public DbSet<SM_CATEGORIA_SERVICIO> SM_CATEGORIA_SERVICIO { get; set; }
        public DbSet<SM_CLAUSULA_CONTRATO> SM_CLAUSULA_CONTRATO { get; set; }
        public DbSet<SM_CONTRATO_SERVICIO> SM_CONTRATO_SERVICIO { get; set; }
        public DbSet<SM_ESTADO_INSPECCION> SM_ESTADO_INSPECCION { get; set; }
        public DbSet<SM_EXPEDIENTE_SERVICIO> SM_EXPEDIENTE_SERVICIO { get; set; }
        public DbSet<SM_INFORME_INSPECCION> SM_INFORME_INSPECCION { get; set; }
        public DbSet<SM_INFORME_TECNICO> SM_INFORME_TECNICO { get; set; }
        public DbSet<SM_INSPECCION> SM_INSPECCION { get; set; }
        public DbSet<SM_OBSERVACION> SM_OBSERVACION { get; set; }
        public DbSet<SM_RECURSOS> SM_RECURSOS { get; set; }
        public DbSet<SM_SERVICIO> SM_SERVICIO { get; set; }
        public DbSet<SM_SOLICITUD_SERVICIO> SM_SOLICITUD_SERVICIO { get; set; }
    
        public virtual ObjectResult<USP_GSM_BuscarPersona_Result> USP_GSM_BuscarPersona(string nombre, string paterno, string materno)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("Paterno", paterno) :
                new ObjectParameter("Paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("Materno", materno) :
                new ObjectParameter("Materno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GSM_BuscarPersona_Result>("USP_GSM_BuscarPersona", nombreParameter, paternoParameter, maternoParameter);
        }
    
        public virtual ObjectResult<USP_GSM_BuscarServicio_Result> USP_GSM_BuscarServicio(Nullable<int> idServicio, string nombre, Nullable<int> tipo, Nullable<int> pagina, Nullable<int> paginacion)
        {
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("IdServicio", idServicio) :
                new ObjectParameter("IdServicio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var paginacionParameter = paginacion.HasValue ?
                new ObjectParameter("Paginacion", paginacion) :
                new ObjectParameter("Paginacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GSM_BuscarServicio_Result>("USP_GSM_BuscarServicio", idServicioParameter, nombreParameter, tipoParameter, paginaParameter, paginacionParameter);
        }
    
        public virtual ObjectResult<USP_GSM_GetInspeccion_Result> USP_GSM_GetInspeccion(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GSM_GetInspeccion_Result>("USP_GSM_GetInspeccion", idParameter);
        }
    
        public virtual ObjectResult<USP_GSM_ListaInspeccion_Result> USP_GSM_ListaInspeccion(Nullable<int> tipo, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> pagina, Nullable<int> paginacion)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var paginacionParameter = paginacion.HasValue ?
                new ObjectParameter("Paginacion", paginacion) :
                new ObjectParameter("Paginacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GSM_ListaInspeccion_Result>("USP_GSM_ListaInspeccion", tipoParameter, fechaIniParameter, fechaFinParameter, paginaParameter, paginacionParameter);
        }
    }
}
