//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_ESTADO_INFORME_SERVICIO
    {
        public SM_ESTADO_INFORME_SERVICIO()
        {
            this.SM_INFORME_SERVICIO = new HashSet<SM_INFORME_SERVICIO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<SM_INFORME_SERVICIO> SM_INFORME_SERVICIO { get; set; }
    }
}
