//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_EXPEDIENTE_SERVICIO
    {
        public SM_EXPEDIENTE_SERVICIO()
        {
            this.SM_INFORME_TECNICO = new HashSet<SM_INFORME_TECNICO>();
            this.SM_SERVICIO = new HashSet<SM_SERVICIO>();
        }
    
        public int CodigoExpedienteServicio { get; set; }
        public Nullable<System.DateTime> FechaCreación { get; set; }
        public string CuerpoExpediente { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaInactivo { get; set; }
        public string LugarServicioPropuesto { get; set; }
        public int coUsuario { get; set; }
        public int CodigoSolicitudServicio { get; set; }
        public Nullable<int> CodigoPersonaEjecutor { get; set; }
    
        public virtual SM_SOLICITUD_SERVICIO SM_SOLICITUD_SERVICIO { get; set; }
        public virtual ICollection<SM_INFORME_TECNICO> SM_INFORME_TECNICO { get; set; }
        public virtual ICollection<SM_SERVICIO> SM_SERVICIO { get; set; }
    }
}
