//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_INFORME_SERVICIO
    {
        public SM_INFORME_SERVICIO()
        {
            this.SM_MEMORANDUM = new HashSet<SM_MEMORANDUM>();
        }
    
        public int CodigoInformeServicio { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public int CodigoEmpleadoAprobador { get; set; }
        public int CodigoEmpleadoElaborador { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> CodigoServicio { get; set; }
        public string Observacion { get; set; }
    
        public virtual SM_ESTADO_INFORME_SERVICIO SM_ESTADO_INFORME_SERVICIO { get; set; }
        public virtual ICollection<SM_MEMORANDUM> SM_MEMORANDUM { get; set; }
    }
}
