//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_MEMORANDUM
    {
        public int CodigoMemorandum { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
        public int CodigoPersonaNotificacion { get; set; }
        public int CodigoInformeServicio { get; set; }
    
        public virtual SM_INFORME_SERVICIO SM_INFORME_SERVICIO { get; set; }
    }
}
