//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_RECURSOS
    {
        public int CodigoRecurso { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Medidas { get; set; }
        public string MarcaRecomendada { get; set; }
        public Nullable<int> CodigoInformeTecnico { get; set; }
    
        public virtual SM_INFORME_TECNICO SM_INFORME_TECNICO { get; set; }
    }
}
