//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SERVICIO
    {
        public SM_SERVICIO()
        {
            this.SM_CONTRATO_SERVICIO = new HashSet<SM_CONTRATO_SERVICIO>();
            this.SM_INSPECCION = new HashSet<SM_INSPECCION>();
        }
    
        public int CodigoServicio { get; set; }
        public string NombreServicio { get; set; }
        public string DescripcionServicio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string LugarServicio { get; set; }
        public Nullable<int> CodigoTipoServicio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> coUsuario { get; set; }
        public Nullable<int> CodigoCategoriaServicio { get; set; }
        public int CodigoExpedienteServicio { get; set; }
        public Nullable<int> CodigoPersonaResponsable { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual SM_CATEGORIA_SERVICIO SM_CATEGORIA_SERVICIO { get; set; }
        public virtual ICollection<SM_CONTRATO_SERVICIO> SM_CONTRATO_SERVICIO { get; set; }
        public virtual SM_ESTADO_SERVICIO SM_ESTADO_SERVICIO { get; set; }
        public virtual SM_EXPEDIENTE_SERVICIO SM_EXPEDIENTE_SERVICIO { get; set; }
        public virtual ICollection<SM_INSPECCION> SM_INSPECCION { get; set; }
    }
}
