//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Contrato
    {
        public int CodigoContrato { get; set; }
        public Nullable<int> NumeroContrato { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public string CodigoProveedor { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
