//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Local
    {
        public int CodigoLocal { get; set; }
        public string Descripcion { get; set; }
        public string Direcion { get; set; }
        public Nullable<int> Aforo { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
