//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_PlanEvento
    {
        public int CodigoPlanificacion { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<System.DateTime> FechaPlanificacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
