//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_EMPLEADO
    {
        public MA_EMPLEADO()
        {
            this.OP_CUADERNO_OBRA = new HashSet<OP_CUADERNO_OBRA>();
            this.SM_INFORME_TECNICO = new HashSet<SM_INFORME_TECNICO>();
            this.SM_SOLICITUD_SERVICIO = new HashSet<SM_SOLICITUD_SERVICIO>();
            this.SM_SOLICITUD_SERVICIO1 = new HashSet<SM_SOLICITUD_SERVICIO>();
            this.OP_ACTIVIDAD_EJECUCION = new HashSet<OP_ACTIVIDAD_EJECUCION>();
        }
    
        public int idEmpleado { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idCargo { get; set; }
        public Nullable<int> idArea { get; set; }
        public string CodigoEmpleado { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
    
        public virtual MA_AREA MA_AREA { get; set; }
        public virtual MA_CARGO MA_CARGO { get; set; }
        public virtual MA_PERSONA MA_PERSONA { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA> OP_CUADERNO_OBRA { get; set; }
        public virtual ICollection<SM_INFORME_TECNICO> SM_INFORME_TECNICO { get; set; }
        public virtual ICollection<SM_SOLICITUD_SERVICIO> SM_SOLICITUD_SERVICIO { get; set; }
        public virtual ICollection<SM_SOLICITUD_SERVICIO> SM_SOLICITUD_SERVICIO1 { get; set; }
        public virtual ICollection<OP_ACTIVIDAD_EJECUCION> OP_ACTIVIDAD_EJECUCION { get; set; }
    }
}
