//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PERSONA
    {
        public MA_PERSONA()
        {
            this.MA_EMPLEADO = new HashSet<MA_EMPLEADO>();
            this.MA_PERSONA1 = new HashSet<MA_PERSONA>();
            this.MA_USUARIO = new HashSet<MA_USUARIO>();
            this.OP_ENTREGA_MATERIAL = new HashSet<OP_ENTREGA_MATERIAL>();
            this.OP_EXPEDIENTE_TECNICO = new HashSet<OP_EXPEDIENTE_TECNICO>();
            this.OP_EXPEDIENTE_TECNICO1 = new HashSet<OP_EXPEDIENTE_TECNICO>();
            this.OP_EXPEDIENTE_TECNICO2 = new HashSet<OP_EXPEDIENTE_TECNICO>();
            this.MA_PERSONAJURIDICA = new HashSet<MA_PERSONAJURIDICA>();
            this.MA_PERSONANATURAL = new HashSet<MA_PERSONANATURAL>();
            this.SM_EXPEDIENTE_SERVICIO = new HashSet<SM_EXPEDIENTE_SERVICIO>();
            this.SM_INFORME_TECNICO = new HashSet<SM_INFORME_TECNICO>();
            this.SM_INSPECCION = new HashSet<SM_INSPECCION>();
            this.SM_SERVICIO = new HashSet<SM_SERVICIO>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public Nullable<int> idTipoDocIdentidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> idRepresentanteLegal { get; set; }
        public string RUC { get; set; }
    
        public virtual MA_DISTRITO MA_DISTRITO { get; set; }
        public virtual ICollection<MA_EMPLEADO> MA_EMPLEADO { get; set; }
        public virtual MA_TIPODOCUMENTOIDENTIDAD MA_TIPODOCUMENTOIDENTIDAD { get; set; }
        public virtual ICollection<MA_PERSONA> MA_PERSONA1 { get; set; }
        public virtual MA_PERSONA MA_PERSONA2 { get; set; }
        public virtual ICollection<MA_USUARIO> MA_USUARIO { get; set; }
        public virtual ICollection<OP_ENTREGA_MATERIAL> OP_ENTREGA_MATERIAL { get; set; }
        public virtual ICollection<OP_EXPEDIENTE_TECNICO> OP_EXPEDIENTE_TECNICO { get; set; }
        public virtual ICollection<OP_EXPEDIENTE_TECNICO> OP_EXPEDIENTE_TECNICO1 { get; set; }
        public virtual ICollection<OP_EXPEDIENTE_TECNICO> OP_EXPEDIENTE_TECNICO2 { get; set; }
        public virtual ICollection<MA_PERSONAJURIDICA> MA_PERSONAJURIDICA { get; set; }
        public virtual ICollection<MA_PERSONANATURAL> MA_PERSONANATURAL { get; set; }
        public virtual ICollection<SM_EXPEDIENTE_SERVICIO> SM_EXPEDIENTE_SERVICIO { get; set; }
        public virtual ICollection<SM_INFORME_TECNICO> SM_INFORME_TECNICO { get; set; }
        public virtual ICollection<SM_INSPECCION> SM_INSPECCION { get; set; }
        public virtual ICollection<SM_SERVICIO> SM_SERVICIO { get; set; }
    }
}
