//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PROVINCIA
    {
        public MA_PROVINCIA()
        {
            this.MA_DISTRITO = new HashSet<MA_DISTRITO>();
        }
    
        public int idProvincia { get; set; }
        public int idDepartamento { get; set; }
        public string Nombre { get; set; }
    
        public virtual MA_DEPARTAMENTO MA_DEPARTAMENTO { get; set; }
        public virtual ICollection<MA_DISTRITO> MA_DISTRITO { get; set; }
    }
}
