//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_Proveedor
    {
        public int IdPersona { get; set; }
        public int idPersonaJuridica { get; set; }
        public string Rubro { get; set; }
        public string Contacto { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
