//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ACTIVIDAD_EJECUCION
    {
        public OP_ACTIVIDAD_EJECUCION()
        {
            this.OP_CUADERNO_OBRA = new HashSet<OP_CUADERNO_OBRA>();
            this.MA_EMPLEADO = new HashSet<MA_EMPLEADO>();
            this.OP_INFORME_OBRA = new HashSet<OP_INFORME_OBRA>();
        }
    
        public int coActividad { get; set; }
        public string noActividad { get; set; }
        public int coCronograma { get; set; }
        public Nullable<System.DateTime> feInicioProgramada { get; set; }
        public Nullable<System.DateTime> feFinProgramada { get; set; }
        public Nullable<System.DateTime> feInicioEjecucion { get; set; }
        public Nullable<System.DateTime> feFinEjecucion { get; set; }
        public Nullable<decimal> nuCostoDirecto { get; set; }
        public Nullable<int> nuCantidadRRHH { get; set; }
    
        public virtual OP_CRONOGRAMA_EJECUCION OP_CRONOGRAMA_EJECUCION { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA> OP_CUADERNO_OBRA { get; set; }
        public virtual ICollection<MA_EMPLEADO> MA_EMPLEADO { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA { get; set; }
    }
}
