//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_CUADERNO_OBRA_MAQUINARIA
    {
        public int coCuadernoObraMaquinaria { get; set; }
        public Nullable<int> coIncidencia { get; set; }
        public int coMaquinaria { get; set; }
        public string noTrabajoRealizado { get; set; }
        public Nullable<System.DateTime> feInicioActividad { get; set; }
        public Nullable<System.DateTime> feFinActividad { get; set; }
    
        public virtual OP_CUADERNO_OBRA OP_CUADERNO_OBRA { get; set; }
        public virtual OP_MAQUINARIA OP_MAQUINARIA { get; set; }
    }
}
