//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_CRONOGRAMA_EJECUCION
    {
        public OP_CRONOGRAMA_EJECUCION()
        {
            this.OP_ACTIVIDAD_EJECUCION = new HashSet<OP_ACTIVIDAD_EJECUCION>();
        }
    
        public int coCronograma { get; set; }
        public int coExpediente { get; set; }
        public Nullable<System.DateTime> feEmision { get; set; }
        public Nullable<int> nuPlazoEjecucion { get; set; }
    
        public virtual ICollection<OP_ACTIVIDAD_EJECUCION> OP_ACTIVIDAD_EJECUCION { get; set; }
        public virtual OP_EXPEDIENTE_TECNICO OP_EXPEDIENTE_TECNICO { get; set; }
    }
}
