//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ENTREGA_MATERIAL
    {
        public OP_ENTREGA_MATERIAL()
        {
            this.OP_INFORME_OBRA = new HashSet<OP_INFORME_OBRA>();
        }
    
        public int coEntrega { get; set; }
        public Nullable<System.DateTime> feEntregaProgramada { get; set; }
        public Nullable<System.DateTime> feEntregaEfectiva { get; set; }
        public string txObservaciones { get; set; }
        public string noTipoEntrega { get; set; }
        public int coProveedor { get; set; }
        public int coMaterial { get; set; }
        public Nullable<int> nuCantidad { get; set; }
    
        public virtual MA_PERSONA MA_PERSONA { get; set; }
        public virtual OP_MATERIAL OP_MATERIAL { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA { get; set; }
    }
}
