//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_INFORME_OBRA
    {
        public OP_INFORME_OBRA()
        {
            this.OP_ACTIVIDAD_EJECUCION = new HashSet<OP_ACTIVIDAD_EJECUCION>();
            this.OP_CUADERNO_OBRA = new HashSet<OP_CUADERNO_OBRA>();
            this.OP_ENTREGA_MATERIAL = new HashSet<OP_ENTREGA_MATERIAL>();
            this.OP_INFORME_OBRA1 = new HashSet<OP_INFORME_OBRA>();
            this.OP_INFORME_OBRA2 = new HashSet<OP_INFORME_OBRA>();
        }
    
        public int coInforme { get; set; }
        public string nuInforme { get; set; }
        public string txTituloInforme { get; set; }
        public Nullable<System.DateTime> feEmision { get; set; }
        public string txConclusion { get; set; }
        public string txRecomendacion { get; set; }
        public Nullable<int> flEstado { get; set; }
        public int coProyecto { get; set; }
        public string noTipoInforme { get; set; }
    
        public virtual OP_PROYECTO_INVERSION_PUBLICA OP_PROYECTO_INVERSION_PUBLICA { get; set; }
        public virtual ICollection<OP_ACTIVIDAD_EJECUCION> OP_ACTIVIDAD_EJECUCION { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA> OP_CUADERNO_OBRA { get; set; }
        public virtual ICollection<OP_ENTREGA_MATERIAL> OP_ENTREGA_MATERIAL { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA1 { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA2 { get; set; }
    }
}
