//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_CATEGORIA_SERVICIO
    {
        public SM_CATEGORIA_SERVICIO()
        {
            this.SM_SERVICIO = new HashSet<SM_SERVICIO>();
        }
    
        public int CodigoCategoriaServicio { get; set; }
        public string nombreCategoria { get; set; }
        public string descripcionCateogira { get; set; }
    
        public virtual ICollection<SM_SERVICIO> SM_SERVICIO { get; set; }
    }
}
