//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_INFORME_INSPECCION
    {
        public SM_INFORME_INSPECCION()
        {
            this.SM_OBSERVACION = new HashSet<SM_OBSERVACION>();
        }
    
        public int CodigoInformeInspeccion { get; set; }
        public Nullable<System.DateTime> FechaInformeInspeccion { get; set; }
        public string CuerpoInspeccion { get; set; }
        public string DescripcionInforme { get; set; }
        public Nullable<int> CodigoInspeccion { get; set; }
        public int CodigoExpedienteServicio { get; set; }
    
        public virtual SM_INSPECCION SM_INSPECCION { get; set; }
        public virtual ICollection<SM_OBSERVACION> SM_OBSERVACION { get; set; }
    }
}
