//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Data.SQL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SOLICITUD_SERVICIO
    {
        public SM_SOLICITUD_SERVICIO()
        {
            this.SM_EXPEDIENTE_SERVICIO = new HashSet<SM_EXPEDIENTE_SERVICIO>();
        }
    
        public int CodigoSolicitudServicio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string NombreSolicitud { get; set; }
        public string Objetivo { get; set; }
        public string DescripcionSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public int idEmpleadoSolicitante { get; set; }
        public int idEmpleadoAprobador { get; set; }
    
        public virtual MA_EMPLEADO MA_EMPLEADO { get; set; }
        public virtual MA_EMPLEADO MA_EMPLEADO1 { get; set; }
        public virtual ICollection<SM_EXPEDIENTE_SERVICIO> SM_EXPEDIENTE_SERVICIO { get; set; }
    }
}
