//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MunicipalidadSanIsidroEntities_New", "FK_op_proyecto_inversion_publica_ma_via", "MA_VIA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Infraestructura.Data.SQL.MA_VIA), "OP_PROYECTO_INVERSION_PUBLICA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Infraestructura.Data.SQL.OP_PROYECTO_INVERSION_PUBLICA), true)]

#endregion

namespace Infraestructura.Data.SQL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MuniIntegrado : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MuniIntegrado object using the connection string found in the 'MuniIntegrado' section of the application configuration file.
        /// </summary>
        public MuniIntegrado() : base("name=MuniIntegrado", "MuniIntegrado")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MuniIntegrado object.
        /// </summary>
        public MuniIntegrado(string connectionString) : base(connectionString, "MuniIntegrado")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MuniIntegrado object.
        /// </summary>
        public MuniIntegrado(EntityConnection connection) : base(connection, "MuniIntegrado")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OP_PROYECTO_INVERSION_PUBLICA> OP_PROYECTO_INVERSION_PUBLICA
        {
            get
            {
                if ((_OP_PROYECTO_INVERSION_PUBLICA == null))
                {
                    _OP_PROYECTO_INVERSION_PUBLICA = base.CreateObjectSet<OP_PROYECTO_INVERSION_PUBLICA>("OP_PROYECTO_INVERSION_PUBLICA");
                }
                return _OP_PROYECTO_INVERSION_PUBLICA;
            }
        }
        private ObjectSet<OP_PROYECTO_INVERSION_PUBLICA> _OP_PROYECTO_INVERSION_PUBLICA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MA_VIA> MA_VIA
        {
            get
            {
                if ((_MA_VIA == null))
                {
                    _MA_VIA = base.CreateObjectSet<MA_VIA>("MA_VIA");
                }
                return _MA_VIA;
            }
        }
        private ObjectSet<MA_VIA> _MA_VIA;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OP_PROYECTO_INVERSION_PUBLICA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOP_PROYECTO_INVERSION_PUBLICA(OP_PROYECTO_INVERSION_PUBLICA oP_PROYECTO_INVERSION_PUBLICA)
        {
            base.AddObject("OP_PROYECTO_INVERSION_PUBLICA", oP_PROYECTO_INVERSION_PUBLICA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MA_VIA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMA_VIA(MA_VIA mA_VIA)
        {
            base.AddObject("MA_VIA", mA_VIA);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MunicipalidadSanIsidroEntities_New", Name="MA_VIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MA_VIA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MA_VIA object.
        /// </summary>
        /// <param name="coVia">Initial value of the coVia property.</param>
        public static MA_VIA CreateMA_VIA(global::System.Int32 coVia)
        {
            MA_VIA mA_VIA = new MA_VIA();
            mA_VIA.coVia = coVia;
            return mA_VIA;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 coVia
        {
            get
            {
                return _coVia;
            }
            set
            {
                if (_coVia != value)
                {
                    OncoViaChanging(value);
                    ReportPropertyChanging("coVia");
                    _coVia = StructuralObject.SetValidValue(value, "coVia");
                    ReportPropertyChanged("coVia");
                    OncoViaChanged();
                }
            }
        }
        private global::System.Int32 _coVia;
        partial void OncoViaChanging(global::System.Int32 value);
        partial void OncoViaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String noNomVia
        {
            get
            {
                return _noNomVia;
            }
            set
            {
                OnnoNomViaChanging(value);
                ReportPropertyChanging("noNomVia");
                _noNomVia = StructuralObject.SetValidValue(value, true, "noNomVia");
                ReportPropertyChanged("noNomVia");
                OnnoNomViaChanged();
            }
        }
        private global::System.String _noNomVia;
        partial void OnnoNomViaChanging(global::System.String value);
        partial void OnnoNomViaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String noTipoVia
        {
            get
            {
                return _noTipoVia;
            }
            set
            {
                OnnoTipoViaChanging(value);
                ReportPropertyChanging("noTipoVia");
                _noTipoVia = StructuralObject.SetValidValue(value, true, "noTipoVia");
                ReportPropertyChanged("noTipoVia");
                OnnoTipoViaChanged();
            }
        }
        private global::System.String _noTipoVia;
        partial void OnnoTipoViaChanging(global::System.String value);
        partial void OnnoTipoViaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MunicipalidadSanIsidroEntities_New", "FK_op_proyecto_inversion_publica_ma_via", "OP_PROYECTO_INVERSION_PUBLICA")]
        public EntityCollection<OP_PROYECTO_INVERSION_PUBLICA> OP_PROYECTO_INVERSION_PUBLICA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OP_PROYECTO_INVERSION_PUBLICA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "OP_PROYECTO_INVERSION_PUBLICA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OP_PROYECTO_INVERSION_PUBLICA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "OP_PROYECTO_INVERSION_PUBLICA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MunicipalidadSanIsidroEntities_New", Name="OP_PROYECTO_INVERSION_PUBLICA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OP_PROYECTO_INVERSION_PUBLICA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OP_PROYECTO_INVERSION_PUBLICA object.
        /// </summary>
        /// <param name="coProyecto">Initial value of the coProyecto property.</param>
        /// <param name="coVia">Initial value of the coVia property.</param>
        /// <param name="nuValorReferencialPerfil">Initial value of the nuValorReferencialPerfil property.</param>
        public static OP_PROYECTO_INVERSION_PUBLICA CreateOP_PROYECTO_INVERSION_PUBLICA(global::System.Int32 coProyecto, global::System.Int32 coVia, global::System.Decimal nuValorReferencialPerfil)
        {
            OP_PROYECTO_INVERSION_PUBLICA oP_PROYECTO_INVERSION_PUBLICA = new OP_PROYECTO_INVERSION_PUBLICA();
            oP_PROYECTO_INVERSION_PUBLICA.coProyecto = coProyecto;
            oP_PROYECTO_INVERSION_PUBLICA.coVia = coVia;
            oP_PROYECTO_INVERSION_PUBLICA.nuValorReferencialPerfil = nuValorReferencialPerfil;
            return oP_PROYECTO_INVERSION_PUBLICA;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 coProyecto
        {
            get
            {
                return _coProyecto;
            }
            set
            {
                if (_coProyecto != value)
                {
                    OncoProyectoChanging(value);
                    ReportPropertyChanging("coProyecto");
                    _coProyecto = StructuralObject.SetValidValue(value, "coProyecto");
                    ReportPropertyChanged("coProyecto");
                    OncoProyectoChanged();
                }
            }
        }
        private global::System.Int32 _coProyecto;
        partial void OncoProyectoChanging(global::System.Int32 value);
        partial void OncoProyectoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String coSNIP
        {
            get
            {
                return _coSNIP;
            }
            set
            {
                OncoSNIPChanging(value);
                ReportPropertyChanging("coSNIP");
                _coSNIP = StructuralObject.SetValidValue(value, true, "coSNIP");
                ReportPropertyChanged("coSNIP");
                OncoSNIPChanged();
            }
        }
        private global::System.String _coSNIP;
        partial void OncoSNIPChanging(global::System.String value);
        partial void OncoSNIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txDescripcion
        {
            get
            {
                return _txDescripcion;
            }
            set
            {
                OntxDescripcionChanging(value);
                ReportPropertyChanging("txDescripcion");
                _txDescripcion = StructuralObject.SetValidValue(value, true, "txDescripcion");
                ReportPropertyChanged("txDescripcion");
                OntxDescripcionChanged();
            }
        }
        private global::System.String _txDescripcion;
        partial void OntxDescripcionChanging(global::System.String value);
        partial void OntxDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String noNombre
        {
            get
            {
                return _noNombre;
            }
            set
            {
                OnnoNombreChanging(value);
                ReportPropertyChanging("noNombre");
                _noNombre = StructuralObject.SetValidValue(value, true, "noNombre");
                ReportPropertyChanged("noNombre");
                OnnoNombreChanged();
            }
        }
        private global::System.String _noNombre;
        partial void OnnoNombreChanging(global::System.String value);
        partial void OnnoNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 coVia
        {
            get
            {
                return _coVia;
            }
            set
            {
                OncoViaChanging(value);
                ReportPropertyChanging("coVia");
                _coVia = StructuralObject.SetValidValue(value, "coVia");
                ReportPropertyChanged("coVia");
                OncoViaChanged();
            }
        }
        private global::System.Int32 _coVia;
        partial void OncoViaChanging(global::System.Int32 value);
        partial void OncoViaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String txUbicacion
        {
            get
            {
                return _txUbicacion;
            }
            set
            {
                OntxUbicacionChanging(value);
                ReportPropertyChanging("txUbicacion");
                _txUbicacion = StructuralObject.SetValidValue(value, true, "txUbicacion");
                ReportPropertyChanged("txUbicacion");
                OntxUbicacionChanged();
            }
        }
        private global::System.String _txUbicacion;
        partial void OntxUbicacionChanging(global::System.String value);
        partial void OntxUbicacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nuBeneficiarios
        {
            get
            {
                return _nuBeneficiarios;
            }
            set
            {
                OnnuBeneficiariosChanging(value);
                ReportPropertyChanging("nuBeneficiarios");
                _nuBeneficiarios = StructuralObject.SetValidValue(value, "nuBeneficiarios");
                ReportPropertyChanged("nuBeneficiarios");
                OnnuBeneficiariosChanged();
            }
        }
        private Nullable<global::System.Int32> _nuBeneficiarios;
        partial void OnnuBeneficiariosChanging(Nullable<global::System.Int32> value);
        partial void OnnuBeneficiariosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nuValorReferencialPerfil
        {
            get
            {
                return _nuValorReferencialPerfil;
            }
            set
            {
                OnnuValorReferencialPerfilChanging(value);
                ReportPropertyChanging("nuValorReferencialPerfil");
                _nuValorReferencialPerfil = StructuralObject.SetValidValue(value, "nuValorReferencialPerfil");
                ReportPropertyChanged("nuValorReferencialPerfil");
                OnnuValorReferencialPerfilChanged();
            }
        }
        private global::System.Decimal _nuValorReferencialPerfil;
        partial void OnnuValorReferencialPerfilChanging(global::System.Decimal value);
        partial void OnnuValorReferencialPerfilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> feRegistro
        {
            get
            {
                return _feRegistro;
            }
            set
            {
                OnfeRegistroChanging(value);
                ReportPropertyChanging("feRegistro");
                _feRegistro = StructuralObject.SetValidValue(value, "feRegistro");
                ReportPropertyChanged("feRegistro");
                OnfeRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _feRegistro;
        partial void OnfeRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnfeRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String noEstado
        {
            get
            {
                return _noEstado;
            }
            set
            {
                OnnoEstadoChanging(value);
                ReportPropertyChanging("noEstado");
                _noEstado = StructuralObject.SetValidValue(value, true, "noEstado");
                ReportPropertyChanged("noEstado");
                OnnoEstadoChanged();
            }
        }
        private global::System.String _noEstado;
        partial void OnnoEstadoChanging(global::System.String value);
        partial void OnnoEstadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MunicipalidadSanIsidroEntities_New", "FK_op_proyecto_inversion_publica_ma_via", "MA_VIA")]
        public MA_VIA MA_VIA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MA_VIA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "MA_VIA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MA_VIA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "MA_VIA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MA_VIA> MA_VIAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MA_VIA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "MA_VIA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MA_VIA>("MunicipalidadSanIsidroEntities_New.FK_op_proyecto_inversion_publica_ma_via", "MA_VIA", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
