//------------------------------------------------------------------------------
// <auto-generated
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated
//------------------------------------------------------------------------------

namespace Entidades.GSM
{
    using System;
    using System.Collections.Generic;
    
    public   class SM_INSPECCION
    {
        public SM_INSPECCION()
        { 
        }
    
        public int CodigoInspeccion { get; set; }
        public System.DateTime FechaInspeccion { get; set; }
        public int coVia { get; set; }
        public string LugarInspeccion { get; set; }
        public int CodigoServicio { get; set; }
        public int coUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string ResponsableServicio { get; set; }
        public int CodigoPersonaEjecutor { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public System.TimeSpan HoraIni { get; set; }
        public int Estado { get; set; }
    
  
    }
}
