//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DETALLEVIA_URBANIZACION
    {
        public int int_IdDetalleVia { get; set; }
        public int int_IdUrbanizacion { get; set; }
        public int int_IdVia { get; set; }
        public int int_NroCuadraInicio { get; set; }
        public int int_NroCuadraFin { get; set; }
    
        public virtual CT_URBANIZACION CT_URBANIZACION { get; set; }
        public virtual CT_VIA CT_VIA { get; set; }
    }
}
