//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GEOLOCALIZACION
    {
        public int int_IdGeolocalizacion { get; set; }
        public Nullable<int> int_IdZona { get; set; }
        public Nullable<int> int_IdManzana { get; set; }
        public Nullable<int> int_IdLote { get; set; }
        public string var_Marca { get; set; }
        public string var_Referencia { get; set; }
        public Nullable<double> flt_Latitud { get; set; }
        public Nullable<double> flt_Longitud { get; set; }
    
        public virtual CT_LOTE CT_LOTE { get; set; }
        public virtual CT_MANZANA CT_MANZANA { get; set; }
        public virtual CT_ZONA CT_ZONA { get; set; }
    }
}
