//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LOTE
    {
        public CT_LOTE()
        {
            this.CT_GEOLOCALIZACION = new HashSet<CT_GEOLOCALIZACION>();
            this.CT_PREDIO = new HashSet<CT_PREDIO>();
        }
    
        public int int_IdLote { get; set; }
        public Nullable<int> int_IdManzana { get; set; }
        public string var_CodigoLote { get; set; }
        public string var_Nombre { get; set; }
        public Nullable<decimal> dcm_Area { get; set; }
        public string var_Direccion { get; set; }
        public System.DateTime dtm_FechaCreacion { get; set; }
        public Nullable<System.DateTime> dtm_FechaActualizacion { get; set; }
        public System.DateTime dtm_FechaRegistro { get; set; }
    
        public virtual ICollection<CT_GEOLOCALIZACION> CT_GEOLOCALIZACION { get; set; }
        public virtual CT_MANZANA CT_MANZANA { get; set; }
        public virtual ICollection<CT_PREDIO> CT_PREDIO { get; set; }
    }
}
