//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PROPUESTAINSPECCION_EMPLEADO
    {
        public int int_IdPropuestaInspeccion { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<int> int_IdZona { get; set; }
        public Nullable<System.DateTime> dtm_FechaInicio { get; set; }
        public Nullable<System.DateTime> dtm_FechaFin { get; set; }
    
        public virtual CT_PROPUESTAINSPECCION CT_PROPUESTAINSPECCION { get; set; }
        public virtual CT_ZONA CT_ZONA { get; set; }
        public virtual MA_EMPLEADO MA_EMPLEADO { get; set; }
    }
}
