//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SOLICITUD
    {
        public CT_SOLICITUD()
        {
            this.CT_PROPUESTAINSPECCION = new HashSet<CT_PROPUESTAINSPECCION>();
            this.CT_ZONA = new HashSet<CT_ZONA>();
        }
    
        public int int_IdSolicitud { get; set; }
        public string var_NroSolicitud { get; set; }
        public string var_Descripcion { get; set; }
        public System.DateTime dtm_FechaEmision { get; set; }
        public System.DateTime dtm_FechaRegistro { get; set; }
        public int int_IdTipoSolicitud { get; set; }
    
        public virtual ICollection<CT_PROPUESTAINSPECCION> CT_PROPUESTAINSPECCION { get; set; }
        public virtual CT_TIPOSOLICITUD CT_TIPOSOLICITUD { get; set; }
        public virtual ICollection<CT_ZONA> CT_ZONA { get; set; }
    }
}
