//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TIPOVIA
    {
        public CT_TIPOVIA()
        {
            this.CT_VIA = new HashSet<CT_VIA>();
        }
    
        public int int_IdTipoVia { get; set; }
        public string var_Nombre { get; set; }
        public string chr_Siglas { get; set; }
    
        public virtual ICollection<CT_VIA> CT_VIA { get; set; }
    }
}
