//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TIPOSOLICITUD
    {
        public CT_TIPOSOLICITUD()
        {
            this.CT_SOLICITUD = new HashSet<CT_SOLICITUD>();
        }
    
        public int int_IdTipoSolicitud { get; set; }
        public string var_TipoSolicitud { get; set; }
    
        public virtual ICollection<CT_SOLICITUD> CT_SOLICITUD { get; set; }
    }
}
