//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_URBANIZACION
    {
        public CT_URBANIZACION()
        {
            this.CT_DETALLEVIA_URBANIZACION = new HashSet<CT_DETALLEVIA_URBANIZACION>();
        }
    
        public int int_IdUrbanizacion { get; set; }
        public string var_Nombre { get; set; }
    
        public virtual ICollection<CT_DETALLEVIA_URBANIZACION> CT_DETALLEVIA_URBANIZACION { get; set; }
    }
}
