//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_ZONA
    {
        public CT_ZONA()
        {
            this.CT_GEOLOCALIZACION = new HashSet<CT_GEOLOCALIZACION>();
            this.CT_MANZANA = new HashSet<CT_MANZANA>();
        }
    
        public int int_IdZona { get; set; }
        public Nullable<int> int_IdSolicitud { get; set; }
        public string var_CodigoZona { get; set; }
        public string var_Nombre { get; set; }
        public Nullable<decimal> dbl_Area { get; set; }
        public System.DateTime dtm_FechaCreacion { get; set; }
        public Nullable<System.DateTime> dtm_FechaActualizacion { get; set; }
        public System.DateTime dtm_FechaRegistro { get; set; }
    
        public virtual ICollection<CT_GEOLOCALIZACION> CT_GEOLOCALIZACION { get; set; }
        public virtual ICollection<CT_MANZANA> CT_MANZANA { get; set; }
        public virtual CT_SOLICITUD CT_SOLICITUD { get; set; }
    }
}
