//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CARGO
    {
        public MA_CARGO()
        {
            this.MA_EMPLEADO = new HashSet<MA_EMPLEADO>();
        }
    
        public int idCargo { get; set; }
        public string descCargo { get; set; }
        public Nullable<int> UsrRegistra { get; set; }
        public Nullable<System.DateTime> FecRegistra { get; set; }
        public Nullable<int> UsrModifica { get; set; }
        public Nullable<System.DateTime> FecModifica { get; set; }
    
        public virtual ICollection<MA_EMPLEADO> MA_EMPLEADO { get; set; }
    }
}
