//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PERSONA
    {
        public MA_PERSONA()
        {
            this.MA_EMPLEADO = new HashSet<MA_EMPLEADO>();
            this.MA_PERSONA1 = new HashSet<MA_PERSONA>();
            this.MA_USUARIO = new HashSet<MA_USUARIO>();
            this.MA_PERSONAJURIDICA = new HashSet<MA_PERSONAJURIDICA>();
            this.MA_PERSONANATURAL = new HashSet<MA_PERSONANATURAL>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public Nullable<int> idTipoDocIdentidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> idRepresentanteLegal { get; set; }
        public string RUC { get; set; }
    
        public virtual ICollection<MA_EMPLEADO> MA_EMPLEADO { get; set; }
        public virtual ICollection<MA_PERSONA> MA_PERSONA1 { get; set; }
        public virtual MA_PERSONA MA_PERSONA2 { get; set; }
        public virtual ICollection<MA_USUARIO> MA_USUARIO { get; set; }
        public virtual ICollection<MA_PERSONAJURIDICA> MA_PERSONAJURIDICA { get; set; }
        public virtual ICollection<MA_PERSONANATURAL> MA_PERSONANATURAL { get; set; }
    }
}
