//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_USUARIO
    {
        public int coUsuario { get; set; }
        public Nullable<int> coPersona { get; set; }
        public string noLoginUsuario { get; set; }
        public string noClaveUsu { get; set; }
        public Nullable<byte> fiActivo { get; set; }
        public string noIpPc { get; set; }
        public Nullable<System.DateTime> feUltimoLogin { get; set; }
        public Nullable<System.DateTime> feCreacion { get; set; }
        public int coPerfil { get; set; }
    
        public virtual MA_PERFIL MA_PERFIL { get; set; }
        public virtual MA_PERSONA MA_PERSONA { get; set; }
    }
}
