//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Core.Entities.ModeloGestionCatastral
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db2f833638c20949ff9238a2f301222db5Entities : DbContext
    {
        public db2f833638c20949ff9238a2f301222db5Entities()
            : base("name=db2f833638c20949ff9238a2f301222db5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_DETALLEVIA_URBANIZACION> CT_DETALLEVIA_URBANIZACION { get; set; }
        public DbSet<CT_GEOLOCALIZACION> CT_GEOLOCALIZACION { get; set; }
        public DbSet<CT_LOTE> CT_LOTE { get; set; }
        public DbSet<CT_MANZANA> CT_MANZANA { get; set; }
        public DbSet<CT_PREDIO> CT_PREDIO { get; set; }
        public DbSet<CT_PROPUESTAINSPECCION> CT_PROPUESTAINSPECCION { get; set; }
        public DbSet<CT_PROPUESTAINSPECCION_EMPLEADO> CT_PROPUESTAINSPECCION_EMPLEADO { get; set; }
        public DbSet<CT_SOLICITUD> CT_SOLICITUD { get; set; }
        public DbSet<CT_TIPOSOLICITUD> CT_TIPOSOLICITUD { get; set; }
        public DbSet<CT_TIPOVIA> CT_TIPOVIA { get; set; }
        public DbSet<CT_URBANIZACION> CT_URBANIZACION { get; set; }
        public DbSet<CT_VIA> CT_VIA { get; set; }
        public DbSet<CT_ZONA> CT_ZONA { get; set; }
        public DbSet<MA_EMPLEADO> MA_EMPLEADO { get; set; }
    }
}
