//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Adquisicion
    {
        public int CodigoAdquisicion { get; set; }
        public string Producto { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<int> CodigoTipoAdquisicion { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
