//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Comite
    {
        public int CodigoComite { get; set; }
        public string NombreCominte { get; set; }
        public Nullable<System.DateTime> FechaVigenciaIniciao { get; set; }
        public Nullable<System.DateTime> FechaVigenciaFin { get; set; }
        public string CodigoEmpleado { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
