//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Evento
    {
        public int CodigoEvento { get; set; }
        public string Titulo { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionDetalle { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Solicitante { get; set; }
        public Nullable<System.DateTime> FechaEventoInicio { get; set; }
        public Nullable<System.DateTime> FechaEventoFin { get; set; }
        public string HoraEvento { get; set; }
        public string Direccion { get; set; }
        public string CodigoUbigeo { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaEjecucion { get; set; }
        public Nullable<System.DateTime> FechaPlanificacion { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> CodigoTipoEvento { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
