//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_Evaluacion
    {
        public int CodigoEvaluacion { get; set; }
        public Nullable<System.DateTime> FechaEvaluacionInicio { get; set; }
        public Nullable<System.DateTime> FechaEvaluacionFin { get; set; }
        public Nullable<int> CantidadMiembros { get; set; }
        public Nullable<int> Resultado { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
