//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GE_ResultadoEvaluacion
    {
        public int CodigoEvaluacion { get; set; }
        public int CodigoComite { get; set; }
        public Nullable<int> Voto { get; set; }
        public Nullable<System.DateTime> FechaVoto { get; set; }
        public string Comentario { get; set; }
    }
}
