//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DEPARTAMENTO
    {
        public MA_DEPARTAMENTO()
        {
            this.MA_PROVINCIA = new HashSet<MA_PROVINCIA>();
        }
    
        public int idDepartamento { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<MA_PROVINCIA> MA_PROVINCIA { get; set; }
    }
}
