//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PERSONAJURIDICA
    {
        public int idPersonaJuridica { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public string RepresentanteLegal { get; set; }
    
        public virtual MA_PERSONA MA_PERSONA { get; set; }
    }
}
