//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PERSONANATURAL
    {
        public int idPersonaNatural { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string NroDocIdentidad { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
    
        public virtual MA_PERSONA MA_PERSONA { get; set; }
    }
}
