//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TIPODOCUMENTOIDENTIDAD
    {
        public MA_TIPODOCUMENTOIDENTIDAD()
        {
            this.MA_PERSONA = new HashSet<MA_PERSONA>();
        }
    
        public int idTipoDocIdentidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MA_PERSONA> MA_PERSONA { get; set; }
    }
}
