//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_USUARIO
    {
        public MA_USUARIO()
        {
            this.OP_CUADERNO_OBRA = new HashSet<OP_CUADERNO_OBRA>();
            this.OP_CUADERNO_OBRA1 = new HashSet<OP_CUADERNO_OBRA>();
        }
    
        public int coUsuario { get; set; }
        public Nullable<int> coPersona { get; set; }
        public string noLoginUsuario { get; set; }
        public string noClaveUsu { get; set; }
        public Nullable<byte> fiActivo { get; set; }
        public string noIpPc { get; set; }
        public Nullable<System.DateTime> feUltimoLogin { get; set; }
        public Nullable<System.DateTime> feCreacion { get; set; }
        public int coPerfil { get; set; }
    
        public virtual MA_PERFIL MA_PERFIL { get; set; }
        public virtual MA_PERSONA MA_PERSONA { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA> OP_CUADERNO_OBRA { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA> OP_CUADERNO_OBRA1 { get; set; }
    }
}
