//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VIA
    {
        public MA_VIA()
        {
            this.OP_PROYECTO_INVERSION_PUBLICA = new HashSet<OP_PROYECTO_INVERSION_PUBLICA>();
        }
    
        public int coVia { get; set; }
        public string noNomVia { get; set; }
        public string noTipoVia { get; set; }
    
        public virtual ICollection<OP_PROYECTO_INVERSION_PUBLICA> OP_PROYECTO_INVERSION_PUBLICA { get; set; }
    }
}
