//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_CUADERNO_OBRA
    {
        public OP_CUADERNO_OBRA()
        {
            this.OP_CUADERNO_OBRA_MAQUINARIA = new HashSet<OP_CUADERNO_OBRA_MAQUINARIA>();
            this.OP_INFORME_OBRA = new HashSet<OP_INFORME_OBRA>();
        }
    
        public int coIncidencia { get; set; }
        public string txDescripcion { get; set; }
        public string noTipoIncidencia { get; set; }
        public string noCriticidad { get; set; }
        public string noCaracteristicaDia { get; set; }
        public Nullable<System.DateTime> feIncidencia { get; set; }
        public Nullable<int> coResponsable { get; set; }
        public Nullable<int> coActividad { get; set; }
        public Nullable<int> coUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> feCreacion { get; set; }
        public Nullable<int> coUsuarioEdicion { get; set; }
        public Nullable<System.DateTime> feEdicion { get; set; }
        public string noIpPc { get; set; }
        public string noUserAgent { get; set; }
    
        public virtual MA_EMPLEADO MA_EMPLEADO { get; set; }
        public virtual MA_USUARIO MA_USUARIO { get; set; }
        public virtual MA_USUARIO MA_USUARIO1 { get; set; }
        public virtual OP_ACTIVIDAD_EJECUCION OP_ACTIVIDAD_EJECUCION { get; set; }
        public virtual ICollection<OP_CUADERNO_OBRA_MAQUINARIA> OP_CUADERNO_OBRA_MAQUINARIA { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA { get; set; }
    }
}
