//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_DOCUMENTO_EXPEDIENTE_TECNICO
    {
        public int coDocumento { get; set; }
        public int coExpediente { get; set; }
        public string nuNroDOcumento { get; set; }
        public Nullable<System.DateTime> feEmision { get; set; }
        public string txDescripcion { get; set; }
        public string txRutaArchivo { get; set; }
        public string noTipoDocExpTec { get; set; }
    
        public virtual OP_EXPEDIENTE_TECNICO OP_EXPEDIENTE_TECNICO { get; set; }
    }
}
