//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_MAQUINARIA
    {
        public OP_MAQUINARIA()
        {
            this.OP_CUADERNO_OBRA_MAQUINARIA = new HashSet<OP_CUADERNO_OBRA_MAQUINARIA>();
        }
    
        public int coMaquinaria { get; set; }
        public string noMaquinaria { get; set; }
        public string noMarca { get; set; }
        public string noModelo { get; set; }
        public Nullable<int> nuAnioFabricacion { get; set; }
        public string noPlaca { get; set; }
        public string noTipo { get; set; }
    
        public virtual ICollection<OP_CUADERNO_OBRA_MAQUINARIA> OP_CUADERNO_OBRA_MAQUINARIA { get; set; }
    }
}
