//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_MATERIAL
    {
        public OP_MATERIAL()
        {
            this.OP_ENTREGA_MATERIAL = new HashSet<OP_ENTREGA_MATERIAL>();
        }
    
        public int coMaterial { get; set; }
        public string noMaterial { get; set; }
        public Nullable<decimal> nuValorReferencial { get; set; }
        public Nullable<decimal> nuStock { get; set; }
        public Nullable<decimal> nuStockMinimo { get; set; }
        public string noUnidadMedida { get; set; }
    
        public virtual ICollection<OP_ENTREGA_MATERIAL> OP_ENTREGA_MATERIAL { get; set; }
    }
}
