//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_PROYECTO_INVERSION_PUBLICA
    {
        public OP_PROYECTO_INVERSION_PUBLICA()
        {
            this.OP_EXPEDIENTE_TECNICO = new HashSet<OP_EXPEDIENTE_TECNICO>();
            this.OP_INFORME_OBRA = new HashSet<OP_INFORME_OBRA>();
        }
    
        public int coProyecto { get; set; }
        public string coSNIP { get; set; }
        public string txDescripcion { get; set; }
        public string noNombre { get; set; }
        public int coVia { get; set; }
        public string txUbicacion { get; set; }
        public Nullable<int> nuBeneficiarios { get; set; }
        public decimal nuValorReferencialPerfil { get; set; }
        public Nullable<System.DateTime> feRegistro { get; set; }
        public string noEstado { get; set; }
    
        public virtual MA_VIA MA_VIA { get; set; }
        public virtual ICollection<OP_EXPEDIENTE_TECNICO> OP_EXPEDIENTE_TECNICO { get; set; }
        public virtual ICollection<OP_INFORME_OBRA> OP_INFORME_OBRA { get; set; }
    }
}
