//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_CONTRATO_SERVICIO
    {
        public SM_CONTRATO_SERVICIO()
        {
            this.SM_CLAUSULA_CONTRATO = new HashSet<SM_CLAUSULA_CONTRATO>();
        }
    
        public int CodigoContratoServicio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> coUsuario { get; set; }
        public int CodigoServicio { get; set; }
    
        public virtual ICollection<SM_CLAUSULA_CONTRATO> SM_CLAUSULA_CONTRATO { get; set; }
        public virtual SM_SERVICIO SM_SERVICIO { get; set; }
    }
}
